disabled_rules:
  - trailing_whitespace
  - line_length
  - file_length
  - type_body_length
  - function_body_length
  - cyclomatic_complexity
  - identifier_name
  - force_cast
  - force_try
  - opening_brace
  - trailing_newline
  - comma
  - implicit_optional_initialization
  - large_tuple
  - empty_count
  - vertical_whitespace
  - colon
  - statement_position
  - for_where
  - trailing_comma
  - vertical_parameter_alignment

excluded:
  - sereviaTests

reporter: "xcode"
